### PR TITLE
Rails 5

### PR DESCRIPTION
**Pull request by esambo**
## Documentation
- Rails 5 support
- use Ruby 2.4

### CODE REVIEW

**Comment by baburdick** [comment]
Hi @esambo. Thanks for your PR!

A couple of questions: Have you verified that these changes allow this gem to function with Rails v5+? And instead of removing the Rails version cap, can you exclude Rails v6+?

**Comment by baburdick** [comment]
(By verification I mean that a full spec run passes under each of the versions of Rails the gemspec now says this gem supports.)

**Comment by MityaLiu** [comment]
@baburdick 
Finished in 2.946836s, 621.3444 runs/s, 756.0652 assertions/s.
1831 runs, 2228 assertions, 0 failures, 0 errors, 0 skips

**Comment by baburdick** [comment]
Awesome. Thanks @MityaLiu! @albertosaurus is taking a look.

**Comment by albertosaurus** [comment]
I'm planning to merge this over the weekend unless I find a showstopper problem.

**Comment by baburdick** [comment]
Confirmed that tests pass.

**Pull request merged**
